"""create phase 2 data model

Revision ID: 0420e0de49e9
Revises: 
Create Date: 2026-08-14 23:25:13.347221

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '0420e0de49e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Fixed UUIDs for the seed offices, so downgrade() can delete exactly
# these rows (not a blanket table wipe) and a re-run of upgrade() after a
# downgrade produces the same identities.
_HEAD_OFFICE_ID = uuid.UUID("00000000-0000-0000-0000-000000000001")
_KANDY_OFFICE_ID = uuid.UUID("00000000-0000-0000-0000-000000000002")
_MATARA_OFFICE_ID = uuid.UUID("00000000-0000-0000-0000-000000000003")
_VAVUNIYA_OFFICE_ID = uuid.UUID("00000000-0000-0000-0000-000000000004")
_KURUNEGALA_OFFICE_ID = uuid.UUID("00000000-0000-0000-0000-000000000005")
_JAFFNA_OFFICE_ID = uuid.UUID("00000000-0000-0000-0000-000000000006")

_SEED_OFFICE_IDS = [
    _HEAD_OFFICE_ID,
    _KANDY_OFFICE_ID,
    _MATARA_OFFICE_ID,
    _VAVUNIYA_OFFICE_ID,
    _KURUNEGALA_OFFICE_ID,
    _JAFFNA_OFFICE_ID,
]

# office table shape as it exists in *this* migration — a local
# alembic.op.bulk_insert target, not app.models.Office (models.py can
# evolve after this migration is written; this table def must not).
_office_table = sa.table(
    "office",
    sa.column("id", sa.UUID()),
    sa.column("name", sa.String()),
    sa.column("type", sa.String()),
    sa.column("district", sa.ARRAY(sa.String())),
    sa.column("opening_hours", sa.String()),
)


def upgrade() -> None:
    """Upgrade schema."""
    # pgvector's Postgres extension is available in the pgvector/pgvector
    # Docker image but not enabled by default (Phase 1 chose the image,
    # never ran CREATE EXTENSION).
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.CheckConstraint("role IN ('reviewer', 'approver')", name='ck_admin_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('office',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('district', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('opening_hours', sa.String(), nullable=False),
    sa.CheckConstraint("type IN ('head', 'regional', 'ds', 'mission')", name='ck_office_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('source_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('snapshot_path', sa.String(), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.CheckConstraint("document_type IN ('html', 'pdf')", name='ck_source_document_document_type'),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name='ck_source_document_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('device_ref', sa.String(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('outdated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_chunk',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer_type', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.CheckConstraint("answer_type IN ('single', 'boolean', 'district')", name='ck_question_answer_type'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_version',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'approved', 'superseded')", name='ck_rule_version_status'),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('case_answer',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('condition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('attribute', sa.String(), nullable=False),
    sa.Column('operator', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.CheckConstraint("operator IN ('equals', 'lessThan', 'in')", name='ck_condition_operator'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('office_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('freshness_rule', sa.String(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.CheckConstraint("kind IN ('document', 'step', 'prerequisite')", name='ck_requirement_kind'),
    sa.ForeignKeyConstraint(['office_id'], ['office.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_rule',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=True),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('penalty_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('basis', sa.String(), nullable=False),
    sa.CheckConstraint("basis IN ('normal', 'urgent')", name='ck_fee_rule_basis'),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('collected', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['case.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requirement_condition',
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=False),
    sa.Column('negated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ),
    sa.PrimaryKeyConstraint('requirement_id', 'condition_id')
    )
    # ### end Alembic commands ###

    # Seed office directory: BACKEND_PLAN.md Phase 2 — Head Office plus
    # five regional offices, with every one of Sri Lanka's 25 districts
    # covered exactly once across the five regional offices' district
    # arrays. See design.md: this is a geographic-proximity placeholder,
    # not sourced from an official Immigration Dept jurisdiction list —
    # must be verified before it is ever citizen-facing.
    op.bulk_insert(
        _office_table,
        [
            {
                "id": _HEAD_OFFICE_ID,
                "name": "Head Office",
                "type": "head",
                "district": None,
                "opening_hours": "Mon-Fri 08:30-16:15",
            },
            {
                "id": _KANDY_OFFICE_ID,
                "name": "Kandy Regional Office",
                "type": "regional",
                "district": ["Kandy", "Matale", "Nuwara Eliya", "Badulla", "Monaragala"],
                "opening_hours": "Mon-Fri 08:30-16:15",
            },
            {
                "id": _MATARA_OFFICE_ID,
                "name": "Matara Regional Office",
                "type": "regional",
                "district": ["Matara", "Galle", "Hambantota"],
                "opening_hours": "Mon-Fri 08:30-16:15",
            },
            {
                "id": _VAVUNIYA_OFFICE_ID,
                "name": "Vavuniya Regional Office",
                "type": "regional",
                "district": [
                    "Vavuniya",
                    "Mannar",
                    "Mullaitivu",
                    "Anuradhapura",
                    "Polonnaruwa",
                ],
                "opening_hours": "Mon-Fri 08:30-16:15",
            },
            {
                "id": _KURUNEGALA_OFFICE_ID,
                "name": "Kurunegala Regional Office",
                "type": "regional",
                "district": [
                    "Kurunegala",
                    "Puttalam",
                    "Colombo",
                    "Gampaha",
                    "Kalutara",
                    "Kegalle",
                    "Ratnapura",
                    "Ampara",
                    "Batticaloa",
                    "Trincomalee",
                ],
                "opening_hours": "Mon-Fri 08:30-16:15",
            },
            {
                "id": _JAFFNA_OFFICE_ID,
                "name": "Jaffna Regional Office",
                "type": "regional",
                "district": ["Jaffna", "Kilinochchi"],
                "opening_hours": "Mon-Fri 08:30-16:15",
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Remove exactly the seeded rows (not a blanket table wipe), before
    # dropping the tables they live in.
    op.execute(
        sa.delete(_office_table).where(_office_table.c.id.in_(_SEED_OFFICE_IDS))
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requirement_condition')
    op.drop_table('plan_item')
    op.drop_table('fee_rule')
    op.drop_table('requirement')
    op.drop_table('condition')
    op.drop_table('case_answer')
    op.drop_table('rule_version')
    op.drop_table('question')
    op.drop_table('document_chunk')
    op.drop_table('case')
    op.drop_table('source_document')
    op.drop_table('service')
    op.drop_table('office')
    op.drop_table('admin_user')
    # ### end Alembic commands ###

    # Reversibility requirement: leave no orphaned extension either.
    # Safe here since nothing else in this project uses pgvector yet.
    op.execute("DROP EXTENSION IF EXISTS vector")
