"""phase 6.7 document_chunk search_vector

Revision ID: 6a2ed7e40160
Revises: 6d9ba671847d
Create Date: 2026-08-16 15:23:54.612726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a2ed7e40160'
down_revision: Union[str, Sequence[str], None] = '6d9ba671847d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunk', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('english', chunk_text)", persisted=True), nullable=True))
    op.create_index('ix_document_chunk_search_vector', 'document_chunk', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunk_search_vector', table_name='document_chunk', postgresql_using='gin')
    op.drop_column('document_chunk', 'search_vector')
    # ### end Alembic commands ###
