"""phase 4: per-fact source citations and resolution_note

Revision ID: 6abdc581a489
Revises: 0420e0de49e9
Create Date: 2026-08-15 13:13:10.655519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6abdc581a489'
down_revision: Union[str, Sequence[str], None] = '0420e0de49e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution_note',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('primary_source_document_id', sa.UUID(), nullable=False),
    sa.Column('secondary_source_document_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['primary_source_document_id'], ['source_document.id'], ),
    sa.ForeignKeyConstraint(['secondary_source_document_id'], ['source_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.add_column('fee_rule', sa.Column('source_document_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_fee_rule_source_document_id', 'fee_rule', 'source_document',
        ['source_document_id'], ['id'],
    )
    op.add_column('requirement', sa.Column('source_document_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_requirement_source_document_id', 'requirement', 'source_document',
        ['source_document_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_requirement_source_document_id', 'requirement', type_='foreignkey')
    op.drop_column('requirement', 'source_document_id')
    op.drop_constraint('fk_fee_rule_source_document_id', 'fee_rule', type_='foreignkey')
    op.drop_column('fee_rule', 'source_document_id')
    op.drop_table('resolution_note')
    # ### end Alembic commands ###
