"""phase 5: source_document approved_at

Revision ID: 6bdbd1e2cfc3
Revises: 6abdc581a489
Create Date: 2026-08-15 14:31:15.030950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bdbd1e2cfc3'
down_revision: Union[str, Sequence[str], None] = '6abdc581a489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_document', sa.Column('approved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_document', 'approved_at')
    # ### end Alembic commands ###
