"""phase 6.6 document_chunk metadata

Revision ID: 6d9ba671847d
Revises: 6bdbd1e2cfc3
Create Date: 2026-08-16 15:14:31.884437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d9ba671847d'
down_revision: Union[str, Sequence[str], None] = '6bdbd1e2cfc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunk', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunk', 'metadata')
    # ### end Alembic commands ###
