"""phase 6.11 chat_message tool_trace

Revision ID: 748be3ff9279
Revises: 838c4dc58a66
Create Date: 2026-08-17 15:13:21.701908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '748be3ff9279'
down_revision: Union[str, Sequence[str], None] = '838c4dc58a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('tool_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_message', 'tool_trace')
    # ### end Alembic commands ###
