"""phase 6.12 question hint, question_condition, requirement resources

Revision ID: b8879c5949b2
Revises: 748be3ff9279
Create Date: 2026-08-18 13:46:07.605056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8879c5949b2'
down_revision: Union[str, Sequence[str], None] = '748be3ff9279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_condition',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('condition_id', sa.UUID(), nullable=False),
    sa.Column('negated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['condition_id'], ['condition.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'condition_id')
    )
    op.add_column('question', sa.Column('hint', sa.Text(), nullable=True))
    op.add_column('requirement', sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirement', 'resources')
    op.drop_column('question', 'hint')
    op.drop_table('question_condition')
    # ### end Alembic commands ###
