---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	classify(classify)
	record_facts(record_facts)
	next_question(next_question)
	resolve(resolve)
	agent(agent)
	tools(tools)
	verify(verify)
	__end__([<p>__end__</p>]):::last
	__start__ -.-> classify;
	__start__ -.-> next_question;
	agent -.-> __end__;
	agent -.-> tools;
	agent -.-> verify;
	classify --> record_facts;
	next_question -.-> __end__;
	next_question -.-> agent;
	next_question -.-> resolve;
	record_facts --> next_question;
	tools -.-> __end__;
	tools -.-> agent;
	verify -.-> __end__;
	verify -.-> agent;
	resolve --> __end__;
	agent -.-> agent;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
